### ISSUE TITLE
Missing / at line 54 in packnet_sfm_node.py

### ISSUE THREAD

**Issue by Likhith-Sugganahalli** [surfii3z/packnet_sfm_ros#3]
models_path = 'src/packnet_sfm_ros/trained_models/'
line 54, missing / before src.
Error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/idontknow/slam_ws/src/packnet_sfm_rossrc/packnet_sfm_ros/trained_models/PackNet01_MR_velsup_CStoK.ckpt'

EDIT:
also folder src/packnet_sfm should be packnet_sfm_ros or code needs to be changed

**Comment by surfii3z** [comment]
Not sure which script you are running, but I was running it in ROS (without docker) and I got no problem.

Please try to provide the full file path
